### ISSUE TITLE
Need plugin

### ISSUE THREAD

**Issue by ghost** [2439905184/websocket#1]
Hello i saw there too many plugin for godot on GitHub. Will you please make a ironsource plugin for me?

**Comment by 2439905184** [comment]
what types of plugins you need?
Android ironsource pluigns or Editor plugins or third-party Engine module
or GD native?

**Comment by ghost** [comment]
> what types of plugins you need?
> Android ironsource pluigns or Editor plugins or third-party Engine module
> or GD native?

Android ironsource ads plugin like admob. Will you make one.

**Comment by ghost** [comment]
> what types of plugins you need?
> Android ironsource pluigns or Editor plugins or third-party Engine module
> or GD native?

I want to connect with you. How can i ?

**Comment by 2439905184** [comment]
you can send email to 2439905184@qq.com
or send message on QQ(Tecent's software)
my qq is 2439905184.
Discord is blocked in China.
If you have wechat(Tecent's software),you can use it also.
my wechat is 13023335265 .
I am a student,so in the day I may can't reply you fast.

**Comment by ghost** [comment]
> you can send email to 2439905184@qq.com
> or send message on QQ(Tecent's software)
> my qq is 2439905184.
> Discord is blocked in China.
> If you have wechat(Tecent's software),you can use it also.
> my wechat is 13023335265 .
> I am a student,so in the day I may can't reply you fast.

Are you available in WhatsApp. Or Facebook. WeChat and qq aren't supporting in Bangladesh

**Comment by 2439905184** [comment]
> > 您可以发送电子邮件到 [2439905184@qq.com](mailto:2439905184@qq.com) 或在QQ（腾讯的软件）上发送消息，我的qq 2439905184。不和谐在中国被封锁。如果你有微信（腾讯的软件），你也可以使用它。我的微信13023335265。我是一名学生，所以在白天我可能无法快速回复你。
> 
> 您是否可以在WhatsApp中使用。或者Facebook。微信和qq在孟加拉国不支持

I don't have WhatsApp. Can you use Discord in your country?
How often does what's app just block people's accounts? I've had my Twitter blocked (just haven't used it in about two years).

**Comment by ghost** [comment]
> > > 您可以发送电子邮件到 [2439905184@qq.com](mailto:2439905184@qq.com) 或在QQ（腾讯的软件）上发送消息，我的qq 2439905184。不和谐在中国被封锁。如果你有微信（腾讯的软件），你也可以使用它。我的微信13023335265。我是一名学生，所以在白天我可能无法快速回复你。
> > 
> > 您是否可以在WhatsApp中使用。或者Facebook。微信和qq在孟加拉国不支持
> 
> I don't have WhatsApp. Can you use Discord in your country?
> How often does what's app just block people's accounts? I've had my Twitter blocked (just haven't used it in about two years).

Do you use discord? I am on discord

**Comment by 2439905184** [comment]
I use discord.
I am now using it to chat with ktabata (the programmer of suika2 open source
engine).

**Comment by ghost** [comment]
> I use discord.
> I am now using it to chat with ktabata (the programmer of suika2 open source
> engine).

hanif098#1245 

This is my discord id. Please add me

**Comment by 2439905184** [comment]
> 

I have sent a request
